### ISSUE TITLE
Member Types at BP Registration

### ISSUE THREAD

**Issue by romanzy** [lmoffereins/bp-xprofile-field-for-member-types#1]
Hi Laurens,

I discovered your fantastic BP plugin, a solution I was hoping for for months. I use it together with bp-mt-extended by iMath (https://github.com/imath/bp-mt-extended). 

I hope that your code will become a part of BuddyPress 2.4.

The only thing I still need is setting user member types during registration (xProfile). There is a solution published by Danbp (https://buddypress.org/support/topic/2-2-member-types-setting-user-member-types-during-registration-xprofile/), but it doesn't work together with your and iMath's plugin.

You can't help me out with a snippet to make this happen? I would appreciate very very much.

Thank you in advance,

Romanzy

**Comment by danbp** [comment]
Hi Romanzy,

i'm still using the code i published on the BP forum and now together with this awesome plugin, and everything is working !
Users can select a member type on registration page, and with help of Member Types at BP Registration plugin,each of them has now an assigned field.

**Comment by romanzy** [comment]
Hi Dan,

Can you publish your bp-custom.php? I get in a loop when I use your code, not able to make it work... Thank you if you can.

**Comment by danbp** [comment]
Hello,

here a brand new bp-custom.php file containing all MT code i actually use.
https://gist.github.com/chouf1/7d847ea760a577fe7081

If you already have such a file with some other custom code, remove it and use this one for testing. If all is OK, you can merge them to your need.

**Comment by romanzy** [comment]
That’s awesome. Thank you very much Dan.

I will try it immediately.

**Comment by imath** [comment]
Hi, i've been looking at this, i think to have different registration forms by member type, BuddyPress core needs to be adapted see : https://buddypress.trac.wordpress.org/ticket/5192#comment:24

**Comment by romanzy** [comment]
Thank you Matthieu. I appreciate very much that you spend time on this matter.

**Comment by danbp** [comment]
Hey Romanzy,

any feedback of my code?

**Comment by romanzy** [comment]
Updated Comment:

Dan,

Your code is working well. The Google Chrome problem is caused by something else, not by your code. 
I'm sorry for my former confusing message, but I'm not so technical as all of you are. 

Romanzy

---

Hi Dan,

I posted yesterday a feedback below your bp-custom code (https://gist.github.com/chouf1/7d847ea760a577fe7081). Your code is working fine, but I only have a weird problem with Google Chrome when your bp-custom.php file is installed, while it's working well with other browsers.

**Comment by romanzy** [comment]
Dear Matthieu,

I refer to your comment and ticket at https://buddypress.trac.wordpress.org/ticket/5192#comment:24.

After patching the php-files I received these two warnings on the BP registration page, referring to: 
// Visibility - Handled here so as not to be overridden by sloppy use of the // exclude_fields parameter. See bp_xprofile_get_hidden_fields_for_user().

Warning: array_merge(): Argument #2 is not an array in …/plugins/buddypress/bp-xprofile/classes/class-bp-xprofile-group.php on line 324

Warning: implode(): Invalid arguments passed in …/plugins/buddypress/bp-xprofile/classes/class-bp-xprofile-group.php on line 325

For sure you will understand these warnings, and why they happen.

Thank you once again for all your great effort.

**Comment by imath** [comment]
This was to test with BuddyPress trunk version having the patch attached to #5192 ticket applied. Are you testing with latest trunk version + patch in it applied ?

This is not to be used elsewhere than on a dev config.

imath.
http://profiles.wordpress.org/imath/

**Comment by romanzy** [comment]
Of course Matthieu, I realise very well that it's only applicable for a dev setup. 

I applied the applicable patches to both bp-xprofile-field-for-member-types.php and bp-xprofile-functions.php of which my patched versions are downloadable here: https://www.dropbox.com/s/am27bf71a31dlrp/patched_php_files.zip?dl=0.

I did it carefully, checking everything several times.

**Comment by imath** [comment]
Ah sorry, was working on mine.. Will Check again

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
@romanzy 

Checked again, everything works fine. I don't know how you patched the file, but you missed something as they were not the same than mine.

You can download the correct version of the files here https://cldup.com/xPCYAVAIz9.zip

Just in case anyone else wants to test.
1/ Get BuddyPress latest trunk version: https://github.com/buddypress/BuddyPress
2/ Patch it with https://buddypress.trac.wordpress.org/attachment/ticket/5192/5192.bp_xprofile_get_hidden_fields_for_user.patch
3/ Get this plugin
4/ Patch it with https://gist.github.com/imath/60c736673cc3edc804b9
5/ create some member types making sure they have a directory slug see : https://codex.buddypress.org/developer/member-types/#member-specific
6/ Create your profile fields, select your preferences about member types.
7/ Logout and go to registration page.

on site.url/register/ the restricted to a member type field won't display
on site.url/register/member_type_has_directory_slug/ the restricted fields for the corresponding member type will be displayed.

8/ once you tested site.url/register/member_type_has_directory_slug/ , activating the account will automatically set the member type for the account.

**Comment by romanzy** [comment]
OK Matthieu. Sorry for not patching the files correctly. 
I will try your files right away.
Once again very much THANK YOU for all your effort.

**Comment by romanzy** [comment]
You have fulfilled one of my biggest BuddyPress wishes, Matthieu. It's working brilliantly. Can't say enough thank you for everything.

**Comment by imath** [comment]
You're welcome, i'm happy it's working for you too :)

imath.
http://profiles.wordpress.org/imath/

**Comment by romanzy** [comment]
Hi Matthieu,

The latest BP trunk version does not display the xProfile Group Tabs (Base Tab - Custom Tab1 - Custom Tab2) in the Admin. The problem is not related to the patched bp-xprofile-functions.php, so maybe you can check with your colleagues why these tabs are not appearing anymore.

Thank you,

Romanzy

**Comment by imath** [comment]
@romanzy it's working fine for me ?? Weird. Have you tried by deactivating all plugins except BuddyPress ?

**Comment by romanzy** [comment]
It was caused by another plugin. Sorry.

**Comment by lmoffereins** [comment]
Since this issue seems te be solved and, to be honest, wasn't about this repo's code in the first place, _and_ since the main gist of this plugin has [landed in BP core](https://buddypress.trac.wordpress.org/changeset/10022) (!), I suggest a close.
