### ISSUE TITLE
Checkbox issue

### ISSUE THREAD

**Issue by danbp** [lmoffereins/bp-xprofile-field-for-member-types#2]
Hi Laurens,

thank you for this usefull plugin.

When i tick a member type and save, the type is not checked. I need to reedit the field,  tick the box again and resave, to get it assigned.
Not sure if it's an issue or only my buggy browser.

**Comment by lmoffereins** [comment]
Hi Dan, thanks for your bug report. 

I was able to confirm the issue, which ignores saving the member type when creating a **new** field. I will try to release a fix in the coming days.

**Comment by lmoffereins** [comment]
@chouf1 The issue appears to be related to a bug in BuddyPress for which I've filed a ticket on trac: https://buddypress.trac.wordpress.org/ticket/6545. For now I've created a temporary workaround. Please confirm if the provided fix solves your issue :)

**Comment by danbp** [comment]
Confirmed: the fix is working for your plugin. Thank you

**Comment by lmoffereins** [comment]
@chouf1 Great :) The plugin is now tagged 1.0.1 with this fix.

FYI, the bug in BuddyPress was almost instantly fixed in [r9983](https://buddypress.trac.wordpress.org/changeset/9983) and [r9986](https://buddypress.trac.wordpress.org/changeset/9986).
